- hosts: all


  vars:
  
    - username: ngs
    
    - source_dir: /ngs/software/src
    - soft_dir: /ngs/software/apps
    - modules_dir: /ngs/software/modules
    - ref_dir: /ngs/prod/reference
    - work_dir: /ngs/prod/scratch
    - archive_dir: "{{ ngs_share_dir }}/miseq_results"
    - test_data_dir: /ngs/test/raw_data
    - test_work_dir: /ngs/test/scratch
    - test_archive_dir: /ngs/test/archive

    - ngs_share_dir: /mnt/ngs_data
    - ngs_share_dir_source: 172.21.0.91:/storage/data
    - miseq_raw_dir: /mnt/miseq_raw
    - miseq_raw_dir_source: 172.21.0.91:/storage/miseq_raw
    - incoming_data_dir: "{{ miseq_raw_dir }}"
    
  pre_tasks:
  
  - name: set timezone to Europe/Warsaw
    timezone:
      name: Europe/Warsaw

  - include: tasks/users.yml
    tags: users

  - name: Create and mount NGS share dirs
    block:
    
      - name: Mount NFS share for miseq raw data
        mount:
          path: "{{ miseq_raw_dir }}"
          src: "{{ miseq_raw_dir_source }}"
          fstype: nfs
          state: mounted
        ignore_errors: yes
    
      - name: Mount NFS share for results
        mount:
          path: "{{ ngs_share_dir }}"
          src: "{{ ngs_share_dir_source }}"
          fstype: nfs
          state: mounted
        ignore_errors: yes
        
    tags: mount

  - name: Create necessary dirs
    file: path={{item}} state=directory mode=ug+rwx group="{{ username }}" owner="{{ username }}"
    with_items:
        - "{{source_dir}}"
        - "{{soft_dir}}"
        - "{{modules_dir}}"
        - "{{ref_dir}}"
        - "{{work_dir}}"
        - "{{archive_dir}}"
        - "{{test_data_dir}}"
        - "{{test_work_dir}}"
        - "{{test_archive_dir}}"

      
  tasks:
  
    - include: tasks/bia-pipeline-common-packages.yml 
      tags: biacommon
    
    - include: tasks/java.yml 
      tags: java
    #- include: tasks/java-link.yml tags=java-link

    - include: tasks/bcl2fastq.yml 
      tags: bcl2fastq 
      version: 2.19.1
      
    - include: tasks/fastqc.yml 
      tags: fastqc 
      version: 0.11.5
      
    - include: tasks/bbmap.yml 
      tags: bbmap 
      version: 36.62

      
    - include: tasks/trimmomatic.yml 
      tags: trimmomatic 
      version: 0.36
    
    - include: tasks/SPAdes.yml 
      tags: spades 
      version: 3.9.0
      
    - include: tasks/quast.yml
      tags: quast 
      version: 4.5
      
    - include: tasks/bia-pipeline.yml 
      tags: biapipeline 
      repo: https://github.com/seru71/zao-bia-pipeline.git 
      version: HEAD

    - include: tasks/htslib.yml 
      tags: htslib 
      version: 1.6

    - include: tasks/samtools.yml 
      tags: samtools 
      version: 1.6 
      htslib_version: 1.6

    - include: tasks/bwa.yml 
      tags: bwa
      version: 0.7.13
    
    - include: tasks/freebayes.yml 
      tags: freebayes
      version: 1.1.0

      
#    - include: tasks/bcftools.yml tags=bcftools version=1.2
#    - include: tasks/vcftools.yml tags=vcftools version=0.1.12b

   
