- hosts: all

  vars:
    - source_dir: /software/src
    - soft_dir: /software/apps
    - modules_dir: /software/modules
    - ref_dir: /references

  pre_tasks:
    - name: Create necessary dirs
      file: path={{item}} state=directory mode=ug+rwx group="{{ ansible_user_id }}" owner="{{ ansible_user_id }}"
      become: true
      become_user: root
      with_items:
        - "{{source_dir}}"
        - "{{soft_dir}}"
        - "{{modules_dir}}"
        - "{{ref_dir}}"
      
  tasks:
    - include: tasks/bia-pipeline-common-packages.yml tags=biacommon
    - include: tasks/java.yml 
    #- include: tasks/java-link.yml tags=java-link

    - include: tasks/bcl2fastq.yml tags=bcl2fastq version=2.19.1
    - include: tasks/fastqc.yml tags=fastqc version=0.11.5
    - include: tasks/bbmap.yml tags=bbmap version=36.62
    - include: tasks/trimmomatic.yml tags=trimmomatic version=0.36
    - include: tasks/SPAdes.yml tags=spades version=3.9.0
    - include: tasks/quast.yml tags=quast version=4.5

    - include: tasks/bia-pipeline.yml tags=biapipeline repo=https://github.com/seru71/bia-pipeline.git version=HEAD
    
#    - include: tasks/bwa.yml tags=bwa
#    - include: tasks/htslib.yml tags=htslib version=1.3.1
#    - include: tasks/samtools.yml tags=samtools version=1.3.1 htslib_version=1.3.1
#    - include: tasks/bcftools.yml tags=bcftools version=1.2
#    - include: tasks/vcftools.yml tags=vcftools version=0.1.12b
