- hosts: all


  vars:
  
    - username: ngs
    
    - source_dir: /ngs/software/src
    - soft_dir: /ngs/software/apps
    - modules_dir: /ngs/software/modules
    - ref_dir: /ngs/prod/reference
    #- data_dir: /ngs/prod/data_tmp
    - work_dir: /ngs/prod/scratch
    - archive_dir: /ngs/prod/archive
    - test_data_dir: /ngs/test/raw_data
    - test_work_dir: /ngs/test/scratch
    - test_archive_dir: /ngs/test/archive

    - incoming_data_dir: /mnt/data/miseq_incoming
    - incoming_dir_NFS_share: //NFS/share
    - cifs_credentials_file: /root/cifs.credentials
    - cifs_mount_username: username
    - cifs_mount_password: password


  pre_tasks:
  
  - name: set timezone to Europe/Warsaw
    timezone:
      name: Europe/Warsaw

  - name: create ngs group
    group:
      name: "{{ username }}"
      state: present

  - name: create ngs user
    user:
      name: "{{ username }}"
      shell: /bin/bash
      comment: "NGS user"
      group: "{{ username }}"
      state: present

  - name: add public key
    lineinfile:
      path: /home/{{ username }}/.ssh/authorized_keys
      line: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDpvdk3hf2oU3VxMob5O5jFFFw5TGaK8BbG/fX36S4pTV6sq8khANZtBoTIpNz07U88AgMLFuuuHtwwWZzKnhPkSbhru8is9Y5X88hCYQ2aNYkIXEoFtGMW9CDAmvRJlrozj8wNCLPjsr2tCTbkFZNoOqQuvd+53zy3obNrPv83DCT0fFGrtPjoRUB8pcJR4PKRod587x/8rqY985XvzJoHGjLCNB8H7zi5yK16Qee6EQvNXrQs9N0Ed+q6AFUME169+IMP54Ocl16Q/DTICgmSQRIaNxrqUArHYvunRgc/jwRK0yKevP/2+bxYq8EvXqf+q3igKfXrIX+l2S5hJeLt'
      create: yes

  - name: Create necessary dirs
    file: path={{item}} state=directory mode=ug+rwx group="{{ username }}" owner="{{ username }}"
    with_items:
        - "{{source_dir}}"
        - "{{soft_dir}}"
        - "{{modules_dir}}"
        - "{{ref_dir}}"
        - "{{work_dir}}"
        - "{{archive_dir}}"
        - "{{test_data_dir}}"
        - "{{test_work_dir}}"
        - "{{test_archive_dir}}"

  - name: Create and mount incoming dir
    block:
      - file: path="{{incoming_data_dir}}" state=directory mode="a+rx"
      
      - name: save credentials in file (DOES NOT overwrite) 
        shell: echo "username={{cifs_mount_username}}\npassword={{cifs_mount_password}}" > {{cifs_credentials_file}}
        args:
            creates: "{{cifs_credentials_file}}"
            
      - name: Mount NFS share
        mount:
          path: "{{ incoming_data_dir }}"
          src: "{{ incoming_dir_NFS_share }}"
          fstype: cifs
          opts: "credentials=/root/cifs.credentials,uid={{ username }},gid={{ username }}"
          state: mounted
        ignore_errors: yes
    tags: mount

      
  tasks:
  
    - include: tasks/bia-pipeline-common-packages.yml tags=biacommon
    
    - include: tasks/java.yml 
    #- include: tasks/java-link.yml tags=java-link

    - include: tasks/bcl2fastq.yml 
      tags: bcl2fastq 
      version: 2.19.1
      
    - include: tasks/fastqc.yml 
      tags: fastqc 
      version: 0.11.5
      
    - include: tasks/bbmap.yml 
      tags: bbmap 
      version: 36.62
      
    - include: tasks/trimmomatic.yml 
      tags: trimmomatic 
      version: 0.36
    
    - include: tasks/SPAdes.yml 
      tags: spades 
      version: 3.9.0
      
    - include: tasks/quast.yml
      tags: quast 
      version: 4.5
      
    - include: tasks/bia-pipeline.yml 
      tags: biapipeline 
      repo: https://github.com/seru71/zao-bia-pipeline.git 
      version: HEAD
    
#    - include: tasks/bwa.yml tags=bwa
#    - include: tasks/htslib.yml tags=htslib version=1.3.1
#    - include: tasks/samtools.yml tags=samtools version=1.3.1 htslib_version=1.3.1
#    - include: tasks/bcftools.yml tags=bcftools version=1.2
#    - include: tasks/vcftools.yml tags=vcftools version=0.1.12b

   
