
- name: Download and unpack BBMap
  block:
    - get_url:
        url=http://sourceforge.net/projects/bbmap/files/BBMap_{{version}}.tar.gz/download
        dest="{{source_dir}}/BBMap-{{version}}.tgz"
    - file: dest="{{ soft_dir }}/BBMap-{{version}}" state=directory mode=0755 owner="{{ username }}" group="{{ username }}" recurse=yes
    - unarchive: 
        src: "{{ source_dir }}/BBMap-{{version}}.tgz"
        dest: "{{ soft_dir }}/BBMap-{{version}}"
        copy: no
        creates: "{{ soft_dir }}/BBMap-{{version}}/bbmap/bbmap.sh"
  become: yes
  become_user: "{{ username }}"
    

# Fix file permissions
- shell: find {{ soft_dir }}/BBMap-{{version}} -type d -exec chmod 0755 {} \; ; find {{ soft_dir }}/BBMap-{{version}} -type f -exec chmod 0644 {} \; ; chmod 0755 {{ soft_dir }}/BBMap-{{version}}/bbmap/*.sh

