- name: Update APT cache
  apt: update_cache=yes cache_valid_time=3600

- name: Install packages
  apt: pkg={{item}} state=present
  with_items:
    - mosh
    - tmux
    - byobu
    - build-essential
    - gcc
    - git
    - tcl
    - zsh
    - vim
    - curl
    - python-pip
    - python-dev
    - python-ruffus
    - python-drmaa
    - pigz
    - bedtools
    - cmake
    - libzmq3-dev
    - libncurses5-dev
    - zlib1g-dev
    - zip
    - liblzma-dev
    - libblas-dev
    - libcurl4-openssl-dev
