
- name: Download and install BWA
  block:
  
    - name: Download BWA
      get_url:
        url: http://sourceforge.net/projects/bio-bwa/files/bwa-{{version}}.tar.bz2
        dest: "{{source_dir}}/bwa-{{version}}.tar.bz2"

    - name: Uncompress BWA
      unarchive:
        src: "{{ source_dir }}/bwa-{{version}}.tar.bz2"
        dest: "{{ source_dir }}"
        copy: no

    - name: Build and Install BWA
      shell: cd {{ source_dir }}/bwa-{{version}}; make && mkdir -p "{{ soft_dir }}/bwa-{{version}}/bin" && cp bwa qualfa2fq.pl xa2multi.pl "{{ soft_dir }}/bwa-{{version}}/bin"
      args:
        creates: "{{ soft_dir }}/bwa-{{version}}/bin/bwa"
        
  become: yes
  become_user: "{{ username }}"

