- name: Download and install FastQC
  block:
  
    - name: Download FastQC
      get_url:
        url: http://www.bioinformatics.babraham.ac.uk/projects/fastqc/fastqc_v{{version}}.zip
        dest: "{{ source_dir }}/fastqc_v{{ version }}.zip"

    - name: Uncompress FastQC
      unarchive:
        src: "{{ source_dir }}/fastqc_v{{ version }}.zip"
        dest: "{{ source_dir }}"
        copy: no

    - name: Move FastQC to a version specific directory
      command: mv {{ source_dir }}/FastQC {{ soft_dir }}/FastQC-{{ version }} creates={{ soft_dir }}/FastQC-{{ version }}

    - file: path="{{ soft_dir }}/FastQC-{{ version }}/fastqc" mode="a+x"      
  become: yes
  become_user: "{{ username }}"

