
- name: Setup samtools
  block:
  
    - name: Download samtools
      get_url:
        url=https://github.com/samtools/samtools/archive/{{version}}.tar.gz
        dest={{source_dir}}/samtools-{{version}}.tar.gz

    - name: Uncompress samtools
      unarchive: 
        src: "{{ source_dir }}/samtools-{{version}}.tar.gz"
        dest: "{{ source_dir }}"
        copy: no
        creates: "{{ source_dir }}/samtools-{{version}}/README"

    - name: Build and Install samtools
      shell: cd {{ source_dir }}/samtools-{{version}}; make install prefix="{{ soft_dir }}/samtools-{{version}}" HTSDIR="../htslib-{{htslib_version}}"
      args:
        creates: "{{ soft_dir }}/samtools-{{version}}/bin/samtools"

  become: yes
  become_user: "{{ ngs_user }}"
