
- name: Download and install SPAdes 
  block:
  
    - name: Download SPAdes
      get_url:
        url: http://spades.bioinf.spbau.ru/release{{version}}/SPAdes-{{version}}-Linux.tar.gz
        dest: "{{source_dir}}/SPAdes-{{version}}-Linux.tar.gz"

    - name: Uncompress SPAdes
      unarchive: 
        src: "{{ source_dir }}/SPAdes-{{version}}-Linux.tar.gz"
        dest: "{{ soft_dir }}"
        copy: no
        creates: "{{ soft_dir}}/SPAdes-{{version}}-Linux/bin/spades"
  
  become: yes
  become_user: "{{ username }}"

