
- name: Download and install Trimmomatic
  block:
 
    - name: Download Trimmomatic
      get_url:
        url: http://www.usadellab.org/cms/uploads/supplementary/Trimmomatic/Trimmomatic-{{version}}.zip
        dest: "{{source_dir}}/Trimmomatic-{{version}}.zip"

    - name: Uncompress Trimmomatic
      unarchive: 
        src: "{{ source_dir }}/Trimmomatic-{{version}}.zip"
        dest: "{{ soft_dir }}"
        copy: no
        creates: "{{ soft_dir }}/Trimmomatic-{{version}}/trimmomatic{{version}}.jar"
  become: yes
  become_user: "{{ username }}"
    
